#!/usr/bin/env python3

import sys
from PIL import Image

def msgToBin(msg):
    res = ''.join('{0:08b}'.format(ord(x), 'b') for x in msg)
    res += '00000000'
    while ((len(res) % 8) % 3 != 0):
        res += '00000000'
    return (res);

def get_last_bit(nb):
    if (nb & 1 == 1):
        return ('1')
    else:
        return ('0')

if (len(sys.argv) != 2):
    print("usage : " +  sys.argv[0] + " path_to_image")
    exit(84);

img = Image.open(sys.argv[1])
matrix = img.load()

msg = ""
binchar = ""
cpt = 0;

for x in range(img.size[0]):
    for y in range(img.size[1]):
        for i in range(3):
            binchar += get_last_bit(matrix[x, y][i])
        if (len(binchar) >= 8):
            tmpchar = "0b" + binchar[:8]
            if (tmpchar == "0b00000000"):
                print("The message hidden in this file is :\n" + msg)
                exit(0)
            msg += chr(int(tmpchar, 2))
            binchar = binchar[8:]
